"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Summary = { patients: any[]; nurses: any[]; floors: any[] };

export default function ManagementPage() {
  const router = useRouter();
  const [summary, setSummary] = useState<Summary | null>(null);
  const [notice, setNotice] = useState("");
  const [share, setShare] = useState<any>(null);
  const [nurse, setNurse] = useState({ name: "", birthDate: "", floor: "", phone: "" });
  const [patient, setPatient] = useState({ fullName: "", birthDate: "", reason: "", allergies: "", emergencyContact: "", emergencyPhone: "", floor: "", bed: "" });
  const [med, setMed] = useState({ patientId: "", name: "", dose: "", times: "", frequency: "", startDate: new Date().toISOString().slice(0, 10), nurseId: "", notes: "" });

  async function load() { const r = await fetch("/api/doctor/summary"); if (!r.ok) { router.push("/login"); return; } setSummary(await r.json()); }
  useEffect(() => { load(); }, []);
  async function post(url: string, body: any, onOk: (x: any) => void) { setNotice(""); const r = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const x = await r.json(); if (!r.ok) { setNotice("No se pudo guardar: " + (x.error || "revisa los datos")); return; } onOk(x); await load(); }
  function createNurse(e: React.FormEvent) { e.preventDefault(); post("/api/nurses", { ...nurse, floor: nurse.floor ? Number(nurse.floor) : undefined }, x => { setShare(x); setNurse({ name: "", birthDate: "", floor: "", phone: "" }); }); }
  function createPatient(e: React.FormEvent) { e.preventDefault(); if (!patient.fullName || !patient.birthDate || !patient.reason || !patient.allergies || !patient.emergencyContact || !patient.emergencyPhone || !patient.floor || !patient.bed) { setNotice("Para ingresar al paciente debes completar datos del paciente, causa, alergias, contacto de emergencia, piso y cama."); return; } post("/api/patients", { ...patient, floor: Number(patient.floor), bed: Number(patient.bed) }, () => { setNotice("Paciente ingresado y cama asignada correctamente."); setPatient({ fullName: "", birthDate: "", reason: "", allergies: "", emergencyContact: "", emergencyPhone: "", floor: "", bed: "" }); }); }
  function createMedication(e: React.FormEvent) { e.preventDefault(); const times = med.times.split(",").map(x => x.trim()).filter(Boolean); if (!times.length && !med.frequency) { setNotice("Indica horarios o una frecuencia, por ejemplo: cada 8 horas."); return; } post("/api/medications", { ...med, times, nurseId: med.nurseId || undefined, frequency: med.frequency || undefined }, () => { setNotice("Orden y tareas del medicamento creadas correctamente."); setMed({ ...med, patientId: "", name: "", dose: "", times: "", frequency: "", nurseId: "", notes: "" }); }); }
  if (!summary) return <main className="page">Cargando…</main>;
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="mark">✚</span> RXList</div><div className="topright"><span>Gestión manual</span><button className="btn ghost" onClick={() => router.push("/doctor")}>Volver al panel</button></div></header>
    <section className="page"><div className="eyebrow">Operación manual</div><h1 className="headline">Altas y órdenes</h1><p className="sub">El ingreso requiere la información mínima del paciente y su ubicación real.</p>{notice && <p className="error">{notice}</p>}
      <div className="dashboard manualgrid">
        <section className="panel"><div className="panelhead"><span className="paneltitle">Agregar enfermera</span><span className="count">Acceso temporal</span></div><form className="manualform" onSubmit={createNurse}><label className="formlabel">Nombre completo<input className="field" value={nurse.name} onChange={e => setNurse({ ...nurse, name: e.target.value })} required /></label><label className="formlabel">Fecha de nacimiento<input className="field" type="date" value={nurse.birthDate} onChange={e => setNurse({ ...nurse, birthDate: e.target.value })} required /></label><label className="formlabel">Piso<select className="field" value={nurse.floor} onChange={e => setNurse({ ...nurse, floor: e.target.value })}><option value="">Sin asignar</option>{summary.floors.map(f => <option key={f.id} value={f.id}>Piso {f.id} · {f.name}</option>)}</select></label><label className="formlabel">Teléfono opcional<input className="field" value={nurse.phone} onChange={e => setNurse({ ...nurse, phone: e.target.value })} /></label><button className="btn primary">Crear enfermera y acceso</button></form>{share && <div className="resetbox"><strong>Acceso creado: {share.email}</strong><span>Contraseña temporal: {share.password}</span></div>}</section>
        <section className="panel"><div className="panelhead"><span className="paneltitle">Agregar paciente</span><span className="count">Información mínima obligatoria</span></div><form className="manualform" onSubmit={createPatient}><label className="formlabel">Datos del paciente · nombre completo<input className="field" value={patient.fullName} onChange={e => setPatient({ ...patient, fullName: e.target.value })} required /></label><label className="formlabel">Fecha de nacimiento<input className="field" type="date" value={patient.birthDate} onChange={e => setPatient({ ...patient, birthDate: e.target.value })} required /></label><label className="formlabel">Causa de ingreso<input className="field" value={patient.reason} onChange={e => setPatient({ ...patient, reason: e.target.value })} required /></label><label className="formlabel">Alergias<input className="field" value={patient.allergies} onChange={e => setPatient({ ...patient, allergies: e.target.value })} placeholder="Ninguna conocida" required /></label><label className="formlabel">Contacto de emergencia<input className="field" value={patient.emergencyContact} onChange={e => setPatient({ ...patient, emergencyContact: e.target.value })} required /></label><label className="formlabel">Teléfono de emergencia<input className="field" value={patient.emergencyPhone} onChange={e => setPatient({ ...patient, emergencyPhone: e.target.value })} required /></label><label className="formlabel">Piso<select className="field" value={patient.floor} onChange={e => setPatient({ ...patient, floor: e.target.value })} required><option value="">Selecciona piso</option>{summary.floors.map(f => <option key={f.id} value={f.id}>Piso {f.id} · {f.name}</option>)}</select></label><label className="formlabel">Cama<input className="field" type="number" min="1" value={patient.bed} onChange={e => setPatient({ ...patient, bed: e.target.value })} required /></label><button className="btn primary">Ingresar paciente</button></form></section>
      </div>
      <section className="panel manualmed"><div className="panelhead"><span className="paneltitle">Agregar medicamento o cuidado</span><span className="count">Requiere paciente ingresado</span></div><form className="manualform medform" onSubmit={createMedication}><label className="formlabel">Paciente<select className="field" value={med.patientId} onChange={e => setMed({ ...med, patientId: e.target.value })} required><option value="">Selecciona un paciente</option>{summary.patients.filter(p => p.status !== "discharged" && typeof p.floor === "number").map(p => <option key={p.id} value={p.id}>{p.fullName} · Piso {p.floor}</option>)}</select></label><label className="formlabel">Medicamento o cuidado<input className="field" value={med.name} onChange={e => setMed({ ...med, name: e.target.value })} placeholder="Nombre indicado por el doctor" required /></label><label className="formlabel">Dosis indicada<input className="field" value={med.dose} onChange={e => setMed({ ...med, dose: e.target.value })} placeholder="Ej. 2 tabletas" /></label><label className="formlabel">Horarios<input className="field" value={med.times} onChange={e => setMed({ ...med, times: e.target.value })} placeholder="07:00, 15:00, 23:00" /><small className="fieldhint">Usa horarios separados por comas o indica una frecuencia.</small></label><label className="formlabel">Frecuencia<input className="field" value={med.frequency} onChange={e => setMed({ ...med, frequency: e.target.value })} placeholder="Cada 8 horas" /></label><label className="formlabel">Fecha de inicio<input className="field" type="date" value={med.startDate} onChange={e => setMed({ ...med, startDate: e.target.value })} required /></label><label className="formlabel">Enfermera responsable<select className="field" value={med.nurseId} onChange={e => setMed({ ...med, nurseId: e.target.value })}><option value="">Asignar después</option>{summary.nurses.filter(n => n.status !== "inactive").map(n => <option key={n.id} value={n.id}>{n.name} · Piso {n.floor}</option>)}</select></label><label className="formlabel fullfield">Observaciones<textarea className="field" value={med.notes} onChange={e => setMed({ ...med, notes: e.target.value })} /></label><button className="btn primary">Crear orden y tareas</button></form></section>
      <section className="panel"><div className="panelhead"><span className="paneltitle">Pacientes actuales</span><span className="count">{summary.patients.length}</span></div><div className="tablewrap"><table className="table"><thead><tr><th>Paciente</th><th>Fecha nacimiento</th><th>Piso</th><th>Estado</th></tr></thead><tbody>{summary.patients.map(p => <tr key={p.id}><td><strong>{p.fullName}</strong></td><td>{p.birthDate}</td><td>{typeof p.floor === "number" ? "Piso " + p.floor : "Sin asignar"}{p.bed ? " · Cama " + p.bed : ""}</td><td>{p.status}</td></tr>)}</tbody></table></div></section>
    </section>
  </main>;
}
